name: Acceptance Tests (EKS)

on:
  workflow_dispatch:
    inputs:
      region:
        description: The AWS region
        default: us-east-1
      azSpan:
        description: The number of AZs to spread cluster nodes across
        default: 2
      clusterVersion:
        description: The EKS cluster version
        default: 1.25
      nodesPerAz:
        description: The number of cluster nodes in each AZ
        default: 2
      instanceType:
        description: The type of EC2 instance to use for cluster nodes
        default: m5.large
      runTests:
        description: The regex passed to the -run option of `go test`
        default: ".*"
      terraformVersion:
        description: Terraform version
        default: 1.4.0

env:
  AWS_REGION: ${{ github.event.inputs.region }}
  TF_VAR_az_span: ${{ github.event.inputs.azSpan }}
  TF_VAR_cluster_version: ${{ github.event.inputs.clusterVersion }}
  TF_VAR_nodes_per_az: ${{ github.event.inputs.nodesPerAz }}
  TF_VAR_instance_type: ${{ github.event.inputs.instanceType }}

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
      - name: Configure AWS Credentials
        uses: hashicorp/doormat-action@566eb1d2575eea7bc17f80710ce8077124aa1ec0 # v1
        with:
          aws-role-arn: ${{ secrets.DOORMAT_AWS_ROLE_ARN }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ github.event.inputs.terraformVersion }}
      - name: Provision EKS Cluster
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/eks
        run: |
          terraform init
          terraform apply --auto-approve
      - name: Run Acceptance Test Suite
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ github.event.inputs.terraformVersion }}
          TESTARGS: -run '${{ github.event.inputs.runTests }}'
          KUBE_CONFIG_PATH: ${{ github.workspace }}/kubernetes/test-infra/eks/kubeconfig
        run: |
          make testacc
      - name: Destroy EKS cluster
        if: always() # we should destroy the cluster even if the tests fail
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/eks
        run: |
          terraform destroy --auto-approve
